import type { NextPage } from 'next'
import Head from 'next/head'
import { useState } from 'react'
import styles from '../styles/Home.module.css'

const Home: NextPage = () => {
  const blue = 'bg-blue-500'
  const red = 'bg-red-500'
  const [buttonColor, setButtonColor] = useState(red)
  const [disabled, setDisabled] = useState(false)

  const newbuttonColor = buttonColor === red ? 'Red' : 'Blue'
  const newbuttonColorClass = buttonColor === red ? blue : red

  const changeBtnColor = () => {
    setButtonColor(newbuttonColorClass)
  }

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <h1>Welcome to Next.js!</h1>
      <a href='#'>This is a Link</a>
      <br />
      <button
        className={`${buttonColor} p-5`}
        style={{ color: 'white' }}
        onClick={() => changeBtnColor()}
        disabled={disabled}
      >
        Change to {newbuttonColor}
      </button>
      <div className='m-5'>
        <input
          type='checkbox'
          id='disable-btn-checkbox'
          defaultChecked={disabled}
          aria-checked={disabled}
          onChange={(e) => setDisabled(e.target.checked)}
        />
        <label className='px-2' htmlFor='disable-btn-checkbox'>
          Disable button
        </label>
      </div>
    </div>
  )
}

export default Home
